TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_rotational_vel: 0.5
  min_in_place_rotational_vel: 0.2

  acc_lim_th: 1.2
  acc_lim_x: 0.9

  holonomic_robot: false

  # goal tolerance parameters
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1
 #latch_xy_goal_tolerance: true
  latch_xy_goal_tolerance: false

  sim_time: 1.7
  #sim_time: 4.5
  sim_granularity: 0.025
  vx_samples: 3
  vtheta_samples: 20

  #Parameters for scoring trajectories
  goal_distance_bias: 0.8
  patch_distance_bias: 0.6
  #goal_distance_bias: 32
  #path_distance_bias: 24
  occdist_scale: 0.01
  heading_lookahead: 0.325

  # using dwa local planner
  dwa: true

  oscillation_reset_dist: 0.05
