TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.01
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.1

  acc_lim_th: 3.2
  acc_lim_x: 1.0

  holonomic_robot: false



#  max_vel_x: 0.13
#  min_vel_x: 0.1
#  max_rotational_vel: 0.1
#  min_in_place_rotational_vel: 0.1

#  acc_lim_th: 0.1
#  acc_lim_x: 0.75
#  acc_lim_y: 0.75

#  holonomic_robot: false

#  dwa: true

#  max_vel_theta: 0.1
#  min_vel_theta: 0
#  min_in_place_vel_theta: 0.1

#  yaw_goal_tolerance: 0.2
#  xy_goal_tolerance: 0.2




#  goal_distance_bias: 0.4

#  sim_time: 1.7
#  sim_granularity: 0.02
#  pdist_scale: 0.2
#  gdist_scale: 0.9
#  occdist_scale: 0.15
#  oscillation_reset_dist: 0.05
#  escape_reset_dist: 0.15
#  escape_reset_theta: 4
#  
#  vtheta_samples: 20
#  heading_lookahead: 0.5
#  escape_vel: -0.1
#  
#  heading_scoring: false
#  heading_scoring_timestep: 0.1
#  simple_attractor: true
#  angular_sim_granularity: 0.02
#  goal_distance_bias: 0.4
