planner_frequency: 2.0

TrajectoryPlannerROS:
  acc_lim_x: 0.75
  acc_lim_y: 0.75
  acc_lim_th: 0.54

  max_vel_x: 0.4
  min_vel_x: 0.01
  max_vel_th: 0.2
  min_vel_theta: 0.0
  min_in_place_vel_th: 0.1  

  holonomic_robot: false

  dwa: false
