obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.25, -0.33], [0.25, 0.33], [-0.55, 0.27], [-0.55, -0.27]]
inflation_radius: 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: camera_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0.2}
