# for details see: http://www.ros.org/wiki/navigation/Tutorials/RobotSetup

obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[0.35, 0.35],[0.35,-0.35],[-0.35,-0.35],[-0.35,0.35]] #cob footprint
footprint: [[0.16, 0.3], [-0.51, 0.225], [-0.51, -0.225], [0.16, -0.3], [0.29, 0]] #delft footprint
#robot_radius: 0.5
inflation_radius: 0.28
max_obstacle_height: 1.4
min_obstacle_height: -1


observation_sources: xtion
xtion: {sensor_frame: camera_link, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}
