obstacle_range: 3.5
raytrace_range: 5
footprint: [[0.25, -0.33], [0.25, 0.33], [-0.55, 0.27], [-0.55, -0.27]]
inflation_radius: 0.35

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: camera_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
