obstacle_range: 2.5
raytrace_range: 3.0
#robot_radius: 0.15 #only uses when the robot is circular
footprint: [[0.35, 0.35],[0.35,-0.35],[-0.35,-0.35],[-0.35,0.35]] #cob footprint
inflation_radius: 0.55

observation_sources: xtion
xtion: {sensor_frame: camera_link, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}
