obstacle_range: 7
raytrace_range: 8
footprint: [[0.30, -0.38], [0.30, 0.38], [-0.60, 0.32], [-0.60, -0.32]]
inflation_radius: 0.35

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: camera_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0.2}
