/* Auto-generated by genmsg_cpp for file /home/robot/git/zuros/zuros_control/zuros_threemxlController/msg/motorMSG.msg */
#ifndef ZUROS_THREEMXLCONTROLLER_MESSAGE_MOTORMSG_H
#define ZUROS_THREEMXLCONTROLLER_MESSAGE_MOTORMSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace zuros_threemxlController
{
template <class ContainerAllocator>
struct motorMSG_ {
  typedef motorMSG_<ContainerAllocator> Type;

  motorMSG_()
  : left_accel(0)
  , left_speed(0)
  , right_accel(0)
  , right_speed(0)
  {
  }

  motorMSG_(const ContainerAllocator& _alloc)
  : left_accel(0)
  , left_speed(0)
  , right_accel(0)
  , right_speed(0)
  {
  }

  typedef int32_t _left_accel_type;
  int32_t left_accel;

  typedef int32_t _left_speed_type;
  int32_t left_speed;

  typedef int32_t _right_accel_type;
  int32_t right_accel;

  typedef int32_t _right_speed_type;
  int32_t right_speed;


  typedef boost::shared_ptr< ::zuros_threemxlController::motorMSG_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zuros_threemxlController::motorMSG_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct motorMSG
typedef  ::zuros_threemxlController::motorMSG_<std::allocator<void> > motorMSG;

typedef boost::shared_ptr< ::zuros_threemxlController::motorMSG> motorMSGPtr;
typedef boost::shared_ptr< ::zuros_threemxlController::motorMSG const> motorMSGConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::zuros_threemxlController::motorMSG_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::zuros_threemxlController::motorMSG_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace zuros_threemxlController

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::zuros_threemxlController::motorMSG_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::zuros_threemxlController::motorMSG_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::zuros_threemxlController::motorMSG_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a2a9eec3fd2b159cc6afa5290066e5df";
  }

  static const char* value(const  ::zuros_threemxlController::motorMSG_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa2a9eec3fd2b159cULL;
  static const uint64_t static_value2 = 0xc6afa5290066e5dfULL;
};

template<class ContainerAllocator>
struct DataType< ::zuros_threemxlController::motorMSG_<ContainerAllocator> > {
  static const char* value() 
  {
    return "zuros_threemxlController/motorMSG";
  }

  static const char* value(const  ::zuros_threemxlController::motorMSG_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::zuros_threemxlController::motorMSG_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#left motor\n\
int32 left_accel\n\
int32 left_speed\n\
\n\
#right motor\n\
int32 right_accel\n\
int32 right_speed\n\
\n\
";
  }

  static const char* value(const  ::zuros_threemxlController::motorMSG_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::zuros_threemxlController::motorMSG_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::zuros_threemxlController::motorMSG_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.left_accel);
    stream.next(m.left_speed);
    stream.next(m.right_accel);
    stream.next(m.right_speed);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct motorMSG_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zuros_threemxlController::motorMSG_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::zuros_threemxlController::motorMSG_<ContainerAllocator> & v) 
  {
    s << indent << "left_accel: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left_accel);
    s << indent << "left_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left_speed);
    s << indent << "right_accel: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right_accel);
    s << indent << "right_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right_speed);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ZUROS_THREEMXLCONTROLLER_MESSAGE_MOTORMSG_H

