planner_frequency: 3.0

TrajectoryPlannerROS:
  acc_lim_x: 0.75
  acc_lim_y: 0.75
  acc_lim_th: 0.54
  max_vel_x: 0.13
  min_vel_x: 0.1
  max_vel_theta: 0.2
  min_vel_theta: 0.0
  min_in_place_vel_theta: 0.1
  sim_time: 1.7
  sim_granularity: 0.02
  pdist_scale: 0.2
  gdist_scale: 0.9
  occdist_scale: 0.15
  oscillation_reset_dist: 0.05
  escape_reset_dist: 0.15
  escape_reset_theta: 4
  vx_samples: 15
  vtheta_samples: 20
  heading_lookahead: 0.5
  holonomic_robot: false
  escape_vel: -0.1
  dwa: false
  heading_scoring: false
  heading_scoring_timestep: 0.1
  simple_attractor: true
  angular_sim_granularity: 0.02
  goal_distance_bias: 0.4
